### PR TITLE
Generate all CML repositories from a single repository

### LINKED ISSUE #100: auto-generate CML example repos
Example repos are painful to update everywhere (e.g. iterative/cml.dev#178 touches all example repos). Should auto-generate them from one source similar to how https://github.com/iterative/example-repos-dev works.

- [ ] https://github.com/iterative/example_cml (/doc/start/github/)
  + [ ] https://github.com/iterative/cml_base_case (/doc/start/github/, /doc/usage?tab=GitHub#example-projects)
  + [ ] https://github.com/iterative/cml_dvc_case (/doc/cml-with-dvc, /doc/usage?tab=GitHub#example-projects)
  + [ ] https://github.com/iterative/cml_tensorboard_case (/doc/usage?tab=GitHub#example-projects)
  + [ ] https://github.com/iterative/cml_cloud_case (/doc/usage?tab=GitHub#example-projects)
- [ ] https://gitlab.com/iterative.ai/example_cml (/doc/start/gitlab/)
  + [ ] https://gitlab.com/iterative.ai/cml-base-case (/doc/start/gitlab/, /doc/usage?tab=GitLab#example-projects-1)
  + [ ] https://gitlab.com/iterative.ai/cml-dvc-case (/doc/usage?tab=GitLab#example-projects-1)
  + [ ] https://gitlab.com/iterative.ai/cml-tensorboard-case (/doc/usage?tab=GitLab#example-projects-1)
  + [ ] https://gitlab.com/iterative.ai/cml-cloud-case (/doc/usage?tab=GitLab#example-projects-1)
  + [ ] https://gitlab.com/iterative.ai/cml-runner-example (/; “CML Use Cases” section; “CML Runner Cloud” tab; “GitLab” switch position)
- [ ] https://bitbucket.org/iterative-ai/example-cml (/doc/start/bitbucket/)
  + [ ] https://bitbucket.org/iterative-ai/cml-base-case (/doc/start/bitbucket/, /doc/usage?tab=Bitbucket#example-projects-2)
  + [ ] https://bitbucket.org/iterative-ai/cml-cloud-case
  + [ ] runner-related demo repos coming soon (https://github.com/iterative/cml.dev/issues/349)
- [ ] https://github.com/iterative/cml-runner-base-case (/)

### PR DESCRIPTION
**Pull request by iesahin**
This one is to add a `generate.bash` script that creates multiple CML example repositories from a single seed repository. 

Closes #100

### CODE REVIEW

**Comment by iesahin** [comment]
This is mostly done. It may have duplicate files that are better to be removed but I didn't check them before your approval.

`generate.bash` 

* Each `$repo` directory in `github` is considered a repository to be placed in `https://github.com/iterative/$repo`
* Each directory in `$repo` directory, (e.g. `github/repo/experiment`) is considered a branch in this repository
* The script clones iterative/example_cml first, copies the files in `github/$repo/$branch/` on top of this as a new branch
* It creates a _push script_ to push all generated repositories at once. 

I didn't add gitlab and bitbucket yet, need to make sure that this is the right approach first. 

* A new `$hub` is (gitlab, bitbucket) is added by adding a directory to `example-cml/$hub`
* Each `$hub` can have its own URL scheme for `git remote`.
* A new repository to github is added by `example-cml/github/$repo`
* A new branch to a repository is added by `example-cml/github/$repo/$branch`
* If you put a `modify-branch.bash` script to `example-cml/github/$repo/$branch` directory, it's run before checking in the files. This file is deleted before commit. So if there are modifications that are better be done in a script rather than copying files, you can put them here. 

There was a `branch/with/slashes` in one of the repositories. The above structure is not compatible with branch names with slashes, so I converted it to a `branch-with-dashes`. 

I didn't use any dvc specific code, only the push script runs `dvc push` and I didn't test it yet. (The push script actually pushes all the repositories and please make sure the repositories are ok before using it.) 

I didn't add support for tags, but if you need them I can add another level of directories for tags. 

This doesn't use any modifications to the committer name and commit date, yet. These can be modified per-hub basis. 

Let me know what you think and would like to see here. Thanks. 

@casperdcl @iterative/cml @shcheklein

**Comment by iesahin** [comment]
I know you're busy with the release but maybe you have time for a quick review to this one: @casperdcl

**Comment by iesahin** [comment]
ping! @casperdcl :)

**Comment by iesahin** [comment]
ping :)

**Comment by 0x2b3bfa0** [comment]
🙏🏼 Thank you very much, @iesahin! This is an awesome stride in the right direction, and we should review it rather sooner than later.

@casperdcl, like the rest of the team, is a bit busy with releases, but we should track this issue somewhere so it doesn't get lost in the meanwhile.

**Comment by 0x2b3bfa0** [comment]
Please ping `@iterative/cml` and @casperdcl if you don't hear back from us.

**Comment by iesahin** [comment]
When do you think you could have more time to review this? @iterative/cml

**Comment by 0x2b3bfa0** [comment]
I guess that the answer is going to be “after the release” 🙃

**Comment by shcheklein** [comment]
@iesahin I think it's almost impossible to review. Let's split into some baby steps please. One project at a time. 100-500 line PRs if possible ...?

**Comment by 0x2b3bfa0** [comment]
> <i><code>example-cml/github/cml-runner-base-case/<b>expeiment</b>/README.md</code></i>

`s/\(expe\)\(iment\)/\1r\2/g`

**Comment by casperdcl** [comment]
I think the [approach](https://github.com/iterative/example-repos-dev/pull/101#issuecomment-1016525400) leads to a lot of code (14k lines) which could be avoided...

1. Many of the branches and even repos are based on each other, I feel applying patches is a better approach?
2. If patch files are too clunky, maybe we can keep things in a single generator repo and a script will push individual branches to different target repos. Whenever something needs to be updated, all branches need to be rebased.

**Comment by 0x2b3bfa0** [comment]
As per https://github.com/iterative/cml/issues/1000#issuecomment-1124628318, [iterative/cml_dvc_case](https://github.com/iterative/cml_dvc_case) should be updated to replace `vl2png ... | cml publish` by `vl2png ... > plot.png` and `cml publish plot.png`

**Comment by iesahin** [comment]
I think with my time constraints until July, I'll close this as is to (maybe) reopen sometime later. Thank you for your reviews.

**Pull request closed without merging**
