### PR TITLE
Dvclive 2.0 updates

### PR DESCRIPTION
**Pull request by dberenbaum**
Updates requirements and adds `Live(dvcyaml=False)`.

### CODE REVIEW

**Comment by dberenbaum** [comment]
I'll look into a separate PR where we take more advantage of the 2.0 features. This one is strictly for backwards compatibility.

**Review by shcheklein — APPROVED** [review]

**Comment by dberenbaum** [comment]
@shcheklein I'm going to redeploy.

**Comment by dberenbaum** [comment]
No rush here @shcheklein but I still don't remember if we have documented all the manual steps at the bottom of `generate.sh`. I remember there being some additional ones last time, so let's wait until you have time to follow up on those and I can make sure to add them to the instructions for next time.

**Comment by shcheklein** [comment]
@dberenbaum hey, yes, I haven't had time to get there yet. Let's not block the update. Since the last steps involve Studio admin let's not share the details in the public repo. We can add a link to the wiki page I think - https://github.com/iterative/studio/wiki/Updating-and-synchronizing-demo-project

**Comment by dberenbaum** [comment]
Thanks @shcheklein. Added instructions in #187 and redeployed everything except for making updates in Studio.

**Comment by shcheklein** [comment]
@dberenbaum done both - reparsed to make sure that the PR link is present and propagated the properties.

**Pull request merged**
