### PR TITLE
Use organization-wide variable for OIDC AWS sandbox role

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
Cleaner, and simpler for @iterative/platform to maintain.

### CODE REVIEW

**Review by daavoo — COMMENTED** [review]
Can we also use it in the generated examples?

https://github.com/iterative/example-repos-dev/tree/master/example-get-started-experiments/code/.github/workflows

**Comment by 0x2b3bfa0** [comment]
Yes! Note, though, that users will have to set those [following these instructions](https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository) rather than on the usual secrets configuration section.

**Comment by dberenbaum** [comment]
Thanks @0x2b3bfa0! Do we use the same role as before? Do we need to update anything in https://www.notion.so/iterative/OpenID-Connect-a34afc51a79d4027a9670ea6a0ba9682#fd60b0894fcc47629d3173be75be537b?

**Comment by 0x2b3bfa0** [comment]
> _Do we use the same role as before?_

Yes, the SandboxUser role.

> _Do we need to update anything in [https://www.notion.so/iterative/OpenID-Connect...](https://www.notion.so/iterative/OpenID-Connect-a34afc51a79d4027a9670ea6a0ba9682#fd60b0894fcc47629d3173be75be537b)?_

I'll probably add a quick note, and link to https://github.com/iterative/example-get-started-experiments/pull/235#discussion_r1322070564.

**Review by jesper7 — APPROVED** [review]

**Pull request merged**
