### PR TITLE
Copy gitlab file

### PR DESCRIPTION
**Pull request by daavoo**

### CODE REVIEW

**Comment by daavoo** [comment]
This is now deployed

**Comment by dberenbaum** [comment]
Sorry, this is another reason we need #200.

It looks like the pipeline is failing in https://gitlab.com/iterative.ai/example-get-started-experiments/-/pipelines. Let's figure that out before we merge this in case there are other changes needed.

**Comment by daavoo** [comment]
Well actually now looks like one triggered by you also failed 😫

**Review by dberenbaum — APPROVED** [review]

**Comment by dberenbaum** [comment]
It's an issue with https://github.com/iterative/itops/pull/1799. It's working now on `master`, so the permissions just need to be updated to work on other branches.

**Pull request merged**
